source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle osx
antigen bundle sudo
antigen bundle z
antigen bundle tmux
antigen bundle thefuck
antigen bundle golang
antigen bundle pyenv
antigen bundle lukechilds/zsh-nvm

antigen theme risto

antigen apply

# vim setup
if [[ "$OSTYPE" == "darwin"* ]]; then
    # Use MacVim instead of system default
    alias vim="mvim -v"
    alias vi="vim"
fi
export EDITOR="vim"
export VISUAL="$EDITOR"

# alias to reattach tmux
alias t="TERM=screen-256color-bce tmux new-session -A -s main"
