# Path to oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# What theme to use
ZSH_THEME="norm"

# Set config for tmux plugin
#ZSH_TMUX_AUTOSTART=true

# Plugins to load
plugins=(git osx sudo z tmux)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Use MacVim instead of system default
    alias vim="mvim -v"
    alias vi="vim"
fi

export EDITOR="vim"
export VISUAL="$EDITOR"

# Initialise `fuck` command
eval "$(thefuck --alias)"

# Use homebrew php
export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# Atom beta
if [[ `command -v atom-beta` ]]; then
    alias atom="atom-beta"
fi

alias t="TERM=screen-256color-bce tmux new-session -A -s main"

export GOPATH="$HOME/Code/go"
export PATH="$GOPATH/bin:$PATH"

