# Path to oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# What theme to use
ZSH_THEME="norm"

# Set config for tmux plugin
ZSH_TMUX_AUTOSTART=true

# Plugins to load
plugins=(git osx sudo z tmux)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Use MacVim instead of system default
    alias vim="mvim -v"
    alias vi="vim"
fi

export EDITOR="vim"
export VISUAL="$EDITOR"

# Initialise `fuck` command
eval "$(thefuck --alias)"
